<?php

/**
 * PluginRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRate');
    }
}