<?php

/**
 * PluginRatableTestObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRatableTestObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginRatableTestObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRatableTestObject');
    }
}